version: '3'

networks:
  monolithic-networks:

services:
  los-gatos-app-container:
    build:
      context: ./los_gatos
      dockerfile: Dockerfile
    environment:
      # SERVER CONFIG
      SERVER_PORT: "8000"
      SERVER_HOST: "0.0.0.0"
      # DATABASE CONFIG
      DB_NAME: "los_gatos_db"
      DB_USER: "root"
      DB_PASS: "1234567890"
      DB_HOST: "los-gatos-db-container" 
      DB_PORT: "3306"
    ports:
      - 8000:8000
    networks:
      - monolithic-networks
    volumes:
      - ./los_gatos/:/opt/app/los_gatos
    depends_on:
      los-gatos-db-container: 
        condition: service_healthy

  los-gatos-db-container:
    build:
      context: ./los_gatos_db
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 10s
        retries: 10      
    networks:
      - monolithic-networks